### ISSUE TITLE
JSON Response is modified before being sent back to caller

### ISSUE THREAD

**Issue by Dragas** [donnysim/ethereal-laravel#12]
There's a possible caveat in `JsonResponse->getContent()` method, where response is modified just before being sent back to request's origin, thus causing an issue with response codes `204` (no content) and `205` (reset content). According to RFC 7231:

> A 204 response is terminated by the first empty line after the header fields because it cannot contain a message body

and

> Since the 205 status code implies that no additional content will be provided, a server MUST NOT generate a payload in a 205 response.  In other words, a server MUST do one of the following for a 205 response: a) indicate a zero-length body for the response by including a Content-Length header field with a value of 0; b) indicate a zero-length payload for the response by including a Transfer-Encoding header field with a value of chunked and a message body consisting of a single chunk of zero-length; or, c) close the connection immediately after sending the blank line terminating the header section."

**Comment by donnysim** [comment]
Fix but v0.2 responses are different than v0.1 so for these situations you can replace it with Laravel json response.

```
response()->json(null, 204);
```
